### ISSUE TITLE
build fail, cannot find "driver/gpio.h"

### ISSUE THREAD

**Issue by Fr4nkGonzalez** [UsefulElectronics/esp32s3-gc9a01-lvgl#2]
Hi,
I have follwing problem when i try to complie.
build fail, cannot find "driver/gpio.h"
any hints?
many thanks
Fra4nk

**Comment by UsefulElectronics** [comment]
"driver/gpio.h" is ESP-IDF component 

Are you building the project inside your ESP-IDF directory ?

Also make sure you IDF_TOOLS_PATH is looking at the correct directory. Mine is C:\Espressif
